apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cest-service
  description: A CEST demo service
  labels:
    testlabel: cest 
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - iac
  links:
    - url: https://cest-service.stelvio.dpgmedia.cloud
      title: AWS crawler
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: experimental
  owner: CEST
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cest-service
  description: AWS crawler
spec:
  type: openapi
  lifecycle: production
  owner: CEST
  system: service
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
